/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>

int main(void)
{
    printf("size of signed char %u\n", sizeof(signed char));
    printf("size of unsigned char %u\n", sizeof(unsigned char));
    printf("size of short int %u\n", sizeof(short int));
    printf("size of unsigned short int %u\n", sizeof( unsigned short int));
    printf("size of int %u\n", sizeof(int));
    printf("size of unsigned int %u\n", sizeof( unsigned int));
    printf("size of long %u\n", sizeof(long));
    printf("size of unsigned long %u\n", sizeof(unsigned long));
    printf("size of long long int %u\n", sizeof(long long int));
    printf("size of unsigned long int %u\n", sizeof(unsigned long int));
    printf("size of float %u\n", sizeof(float));
    printf("size of double %u\n", sizeof(double));
    /* Loop forever */
	for(;;);
}
